#!/bin/env lua

package.path = package.path..";lib/?.lua;spec/?.lua"

require 'bits_spec'
require 'sym_spec'
require 'tuple_spec'
require 'encoder_spec'
require 'decode_spec'
require 'roundtrip_spec'

spec:report()

