#!/usr/bin/env lua -lluacov.tick -lluarocks.require

package.path = package.path..";lib/?.lua;spec/?.lua"

require 'bytes_spec'
require 'bits_spec'
require 'sym_spec'
require 'tuple_spec'
require 'encoder_spec'
require 'decoder_spec'
require 'roundtrip_spec'

spec:report()

